version: '3'
services:
  openbas-dev-pgsql:
    container_name: openbas-dev-pgsql
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: openbas
    volumes:
      - pgsqldata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
  openbas-dev-minio:
    container_name: openbas-dev-minio
    image: minio/minio:RELEASE.2023-11-01T01-57-10Z
    ports:
      - "9002:9000"
      - "9003:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    restart: unless-stopped
volumes:
  pgsqldata:
  s3data:
