services:
  openbas:
    environment:
      - EXECUTOR_CALDERA_ENABLE=true
      - EXECUTOR_CALDERA_URL=${CALDERA_URL:-http://caldera:8888}
      - EXECUTOR_CALDERA_PUBLIC_URL=${CALDERA_PUBLIC_URL:-http://localhost:8888}
      - EXECUTOR_CALDERA_API_KEY=${CALDERA_API_KEY:-ChangeMe}
    depends_on:
      caldera:
        condition: service_healthy